#! /usr/bin/env bash

eval "$(conda shell.bash hook)"

conda activate downscaling

set -euo pipefail

mass_host="mass-cli.jasmin.ac.uk"
sci_host="sci2.jasmin.ac.uk"
xfer_host="xfer1.jasmin.ac.uk"
bp_host="bp"

variable=$1
year=$2
let "start_year=year-1"
domain="london"
frequency="day"

set -x

# Extract (from moose)
# mlde moose extract --variable ${variable} --year ${year}
LANG=C ssh -a -q -o ServerAliveInterval=60 ${mass_host} code/ml-downscaling-emulation/moose-etl/mass-script ${variable} ${year}

# Transform (on sci JASMIN)
~/code/ml-downscaling-emulation/moose-etl/sci-jasmin-script ${variable} ${year}
# LANG=C ssh -a -q -o ServerAliveInterval=60 ${sci_host} code/ml-downscaling-emulation/moose-etl/sci-jasmin-script ${variable} ${year}

# Load (onto BP storage)
for sf in 4 8 16 27 32; do
  set +x
  resolution="2.2km-coarsened-${sf}x"
  filename="${variable}_rcp85_land-cpm_${domain}_${resolution}_01_${frequency}_${start_year}1201-${year}1130.nc"
  file_subpath="${domain}/${resolution}/rcp85/01/${variable}/${frequency}/${filename}"
  jasmin_filepath="/home/users/vf20964/derived_data/moose/${file_subpath}"
  bp_filepath="/user/work/vf20964/moose/${file_subpath}"
  set -x

  ssh -a -q bp mkdir -p $(dirname ${bp_filepath})
  # mkdir -p $(dirname ${bp_filepath})
  ssh -a -q ${xfer_host} scp -oProxyJump=seis ${jasmin_filepath} ${bp_host}:${bp_filepath}
  # scp -a ${xfer_host}:${jasmin_filepath} bp:${bp_filepath}
  rm ${jasmin_filepath}
  # LANG=C ssh -a -q ${sci_host} rm ${jasmin_filepath}
done
