#! /usr/bin/env bash

set -euo pipefail

variable=$1
sf=$2

if [ ${sf} -eq 1 ]
then
  target_resolution=2.2km
else
  target_resolution=2.2km-coarsened-${sf}x
fi

# target_pr is a pseudo-variable for this script to indicate data and grid resolutions should match
# since pr can be used as target and as input variable depending on the resolution
if [[ "${variable}" == "target_pr" ]]
then
  variable="pr"
  variable_resolution=${target_resolution}
else
  variable_resolution="2.2km-coarsened-gcm"
fi

resolution="${variable_resolution}-${target_resolution}"

bp_host=bp-remote

local_dirpath=${DERIVED_DATA}/moose/london/${resolution}/rcp85/01/${variable}/day/
bp_dirpath=/user/work/vf20964/moose/london/${resolution}/rcp85/01/${variable}/day

mkdir -p ${local_dirpath}

for year in 1981 2021 2061; do
  let "dec_year=year-1"
  time_range="${dec_year}1201-${year}1130"
  filename=${variable}_rcp85_land-cpm_london_${resolution}_01_day_${time_range}.nc

  scp ${bp_host}:${bp_dirpath}/${filename} ${local_dirpath}
done
