#! /usr/bin/env bash

set -euo pipefail

variable=$1
domain=$2
target_sf=$3
variable_sf=$4
unscaled_variable_resolution=${5:-"2.2km"}

if [[ ${unscaled_variable_resolution} == "2.2km" ]]; then
  collection="land-cpm"
elif [[ ${unscaled_variable_resolution} == "60km" ]]; then
  collection="land-gcm"
fi

if [ ${target_sf} -eq 1 ]
then
  target_resolution="2.2km"
else
  target_resolution="2.2km-coarsened-${target_sf}x"
fi

# target_pr is a pseudo-variable for this script to indicate data and grid resolutions should match
# since pr can be used as target and as input variable depending on the resolution
if [[ "${variable}" == "target_pr" ]]
then
  variable="pr"
  variable_resolution=${target_resolution}
else
  if [ $variable_sf == "gcm" ]; then
    variable_resolution="${unscaled_variable_resolution}-coarsened-gcm"
  elif [ $variable_sf -eq 1 ]; then
    variable_resolution=${unscaled_variable_resolution}
  else
    variable_resolution="${unscaled_variable_resolution}-coarsened-${variable_sf}x"
  fi
fi

resolution="${variable_resolution}-${target_resolution}"

bp_host=bp-remote

local_dirpath=${DERIVED_DATA}/moose/${domain}/${resolution}/rcp85/01/${variable}/day/
bp_dirpath=/user/work/vf20964/moose/${domain}/${resolution}/rcp85/01/${variable}/day

mkdir -p ${local_dirpath}

for year in 1981 2021 2061; do
  let "dec_year=year-1"
  time_range="${dec_year}1201-${year}1130"
  filename=${variable}_rcp85_${collection}_${domain}_${resolution}_01_day_${time_range}.nc

  scp ${bp_host}:${bp_dirpath}/${filename} ${local_dirpath}
done
