#! /usr/bin/env bash

eval "$(conda shell.bash hook)"

conda activate cuda-downscaling

set -euo pipefail

# some constants and defaults

mass_host="mass-cli.jasmin.ac.uk"
sci_host="sci2.jasmin.ac.uk"
xfer_host="xfer1.jasmin.ac.uk"

frequency="day"
target_sfs=(4)
variable_sfs=(gcm)
target_size=64

declare -A source
source["cpm-vorticity850"]="xwind ywind"
source["gcm-vorticity850"]="xwind ywind"
source["cpm-pr"]="lsrain lssnow"
source["gcm-pr"]="pr"
source["gcm-lin-pr"]="pr"
source["cpm-temp250"]="temp"
source["cpm-temp500"]="temp"
source["cpm-temp700"]="temp"
source["cpm-temp850"]="temp"

# parse commandline arguments

while getopts ":c:v:s:t:d:p:" opt; do
  case ${opt} in
    c)
      collection=${OPTARG}
      ;;
    v )
      data_variable=${OPTARG}
      ;;
    s )
      variable_sfs=(${OPTARG})
      ;;
    t )
      target_sfs=(${OPTARG})
      ;;
    d )
      domain=${OPTARG}
      ;;
    p )
      target_size=${OPTARG}
      ;;
   \? )
     echo "Invalid Option: -${OPTARG}" 1>&2
     exit 1
     ;;
  esac
done
shift $((OPTIND -1))

# compute other helpful values based on constants and args

if [ $collection == "land-cpm" ]; then
  unscaled_variable_resolution="2.2km"
  variable_config_name="cpm-${data_variable}"
elif [ $collection == "land-gcm" ]; then
  unscaled_variable_resolution="60km"
  variable_config_name="gcm-${data_variable}"
else
  >&2 echo "unrecognised collection ${collection}"
  exit 1
fi

src_vars=${source["${variable_config_name}"]}

# do the work

set -x

for year in $@; do

  let "start_year=year-1"

  # Extract (source data from moose to nc format)
  for src_variable in ${src_vars[@]}; do
    mlde moose extract --variable  ${src_variable} --year ${year} --collection ${collection}

    mlde moose convert --variable ${src_variable} --year ${year} --collection ${collection}
  done;

  # Transform (into vorticity on sci JASMIN)

  for target_sf in ${target_sfs[@]}; do
    if [ $target_sf -eq 1 ]; then
      target_resolution="2.2km"
    else
      target_resolution="2.2km-coarsened-${target_sf}x"
    fi
    for variable_sf in ${variable_sfs[@]}; do
      if [ $variable_sf == "gcm" ]; then
        variable_resolution="${unscaled_variable_resolution}-coarsened-gcm"
      elif [ $variable_sf -eq 1 ]; then
        variable_resolution=${unscaled_variable_resolution}
      else
        variable_resolution="${unscaled_variable_resolution}-coarsened-${variable_sf}x"
      fi

      resolution="${variable_resolution}-${target_resolution}"

      mlde moose create-variable --variable ${variable_config_name} --year ${year} --scale-factor ${variable_sf} --domain ${domain} --target-resolution ${target_resolution} --target-size ${target_size}

      # Load (vorticity onto BP storage)
      filename="${data_variable}_rcp85_${collection}_${domain}-${target_size}_${resolution}_01_${frequency}_${start_year}1201-${year}1130.nc"
      config_filename="${variable_config_name}-${year}.yml"
      file_subdirpath="${domain}-${target_size}/${resolution}/rcp85/01/${data_variable}/${frequency}"
      jasmin_dirpath="/home/users/vf20964/derived_data/moose/${file_subdirpath}"
      bp_dirpath="/user/work/vf20964/moose/${file_subdirpath}"

      LANG=C ssh -a -o ServerAliveInterval=60 ${xfer_host} code/ml-downscaling-emulation/moose-etl/xfer-script "${jasmin_dirpath}/${filename}" "${bp_dirpath}/${filename}"
      # including the variable config
      LANG=C ssh -a -o ServerAliveInterval=60 ${xfer_host} code/ml-downscaling-emulation/moose-etl/xfer-script "${jasmin_dirpath}/${config_filename}" "${bp_dirpath}/${config_filename}"
      # Cleanup files copied to BP
      rm "${jasmin_dirpath}/${filename}"
      rm "${jasmin_dirpath}/${config_filename}"
    done;
  done;

  # Clean up (x and y wind components downloaded from moose)
  for src_variable in ${src_vars[@]}; do
    mlde moose clean --variable ${src_variable} --year ${year} --collection ${collection}
  done

  sleep 5
done
