#! /usr/bin/bash

set -euo pipefail

collection=$1
variable=$2
domain=$3
variable_sf=${4:-"gcm"}
size=${5:-64}

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

ts1jobid=$(sbatch -A mass -p mass --time 23:00:00 --parsable ${SCRIPT_DIR}/master-script -c ${collection} -v ${variable} -s ${variable_sf} -d ${domain} -p ${size} $(seq 1981 1 2000))
echo ${ts1jobid}

ts2jobid=$(sbatch -A mass -p mass --time 23:00:00 --parsable --dependency=afterok:${ts1jobid} ${SCRIPT_DIR}/master-script -c ${collection} -v ${variable} -s ${variable_sf} -d ${domain} -p ${size} $(seq 2021 1 2040))
echo ${ts2jobid}

ts3jobid=$(sbatch -A mass -p mass --time 23:00:00 --parsable --dependency=afterok:${ts2jobid} ${SCRIPT_DIR}/master-script -c ${collection} -v ${variable} -s ${variable_sf} -d ${domain} -p ${size} $(seq 2061 1 2080))
echo ${ts3jobid}
