#! /usr/bin/bash

set -euo pipefail

collection=$1
variable=$2
domain=$3
variable_sf=$4
target_sf=$5
size=${6}

job_name="${variable}-${domain}-${size}-${collection}"

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

# TS1
jobid=$(sbatch --job-name ${job_name} -A mass -p mass --time 23:00:00 --parsable ${MASTER_SCRIPT_PATH} -c ${collection} -v ${variable} -s ${variable_sf} -t ${target_sf} -d ${domain} -p ${size} $(seq 1981 1 1990))
echo ${jobid}
jobid=$(sbatch --job-name ${job_name} -A mass -p mass --time 23:00:00 --parsable --dependency=afterok:${jobid} ${MASTER_SCRIPT_PATH} -c ${collection} -v ${variable} -s ${variable_sf} -t ${target_sf} -d ${domain} -p ${size} $(seq 1991 1 2000))
echo ${jobid}

# TS2
jobid=$(sbatch --job-name ${job_name} -A mass -p mass --time 23:00:00 --parsable --dependency=afterok:${jobid} ${MASTER_SCRIPT_PATH} -c ${collection} -v ${variable} -s ${variable_sf} -t ${target_sf} -d ${domain} -p ${size} $(seq 2021 1 2030))
echo ${jobid}
jobid=$(sbatch --job-name ${job_name} -A mass -p mass --time 23:00:00 --parsable --dependency=afterok:${jobid} ${MASTER_SCRIPT_PATH} -c ${collection} -v ${variable} -s ${variable_sf} -t ${target_sf} -d ${domain} -p ${size} $(seq 2040 1 2040))
echo ${jobid}

# TS3
jobid=$(sbatch --job-name ${job_name} -A mass -p mass --time 23:00:00 --parsable --dependency=afterok:${jobid} ${MASTER_SCRIPT_PATH} -c ${collection} -v ${variable} -s ${variable_sf} -t ${target_sf} -d ${domain} -p ${size} $(seq 2061 1 2070))
echo ${jobid}
jobid=$(sbatch --job-name ${job_name} -A mass -p mass --time 23:00:00 --parsable --dependency=afterok:${jobid} ${MASTER_SCRIPT_PATH} -c ${collection} -v ${variable} -s ${variable_sf} -t ${target_sf} -d ${domain} -p ${size} $(seq 2071 1 2080))
echo ${jobid}
