#! /usr/bin/bash

set -euo pipefail

while getopts ":j:" opt; do
  case ${opt} in
    j)
      job_id=${OPTARG}
      ;;
   \? )
     echo "Invalid Option: -${OPTARG}" 1>&2
     exit 1
     ;;
  esac
done
shift $((OPTIND -1))

cmd=$@

if [ $job_id -eq 0 ]; then
  sbatch -A mass -p mass --time 23:00:00 --parsable -- ${cmd}
else
  sbatch -A mass -p mass --time 23:00:00 --parsable  --dependency=afterok:${job_id} -- ${cmd}
fi
