#! /usr/bin/env bash

bp_host="bp"

jasmin_filepath=$1
bp_filepath=$2

set -euo pipefail

ssh -a -J seis ${bp_host} mkdir -p $(dirname ${bp_filepath})
set -x
scp -oProxyJump=seis ${jasmin_filepath} ${bp_host}:${bp_filepath}
