#! /usr/bin/env bash

eval "$(conda shell.bash hook)"

conda activate cuda-downscaling

set -euo pipefail

variable=$1
year=$2
sf=$3
resolution="2.2km-coarsened-${sf}x"
domain="london"

mass_host="mass-cli.jasmin"
sci_host="sci2.jasmin"
xfer_host="xfer1.jasmin"

let "start_year=year-1"
file_subpath="${domain}/${resolution}/rcp85/01/${variable}/day/${variable}_rcp85_land-cpm_${domain}_${resolution}_01_day_${start_year}1201-${year}1130.nc"
remote_filepath="derived_data/moose/${file_subpath}"
local_filepath="${DERIVED_DATA}/moose/${file_subpath}"

set -x

LANG=C ssh -q ${mass_host} code/ml-downscaling-emulation/moose-script ${variable} ${year}
LANG=C ssh -q ${sci_host} code/ml-downscaling-emulation/sci-jasmin-script ${variable} ${year} ${sf}

mkdir -p $(dirname ${local_filepath})
LANG=C scp -q ${xfer_host}:${remote_filepath} ${local_filepath}

LANG=C ssh -q ${sci_host} rm ${remote_filepath}
