#! /usr/bin/env bash

eval "$(conda shell.bash hook)"

conda activate downscaling

set -euo pipefail

variable=$1
year=$2
sf=$3
resolution="2.2km-coarsened-${sf}x"
domain="london"
frequency="day"

mass_host="mass-cli.jasmin"
sci_host="sci2.jasmin.ac.uk"
xfer_host="xfer1.jasmin.ac.uk"

let "start_year=year-1"
file_subpath="${domain}/${resolution}/rcp85/01/${variable}/${frequency}/${variable}_rcp85_land-cpm_${domain}_${resolution}_01_${frequency}_${start_year}1201-${year}1130.nc"
remote_filepath="derived_data/moose/${file_subpath}"
local_filepath="${DERIVED_DATA}/moose/${file_subpath}"

set -x

mlde moose extract --variable ${variable} --year ${year}

LANG=C ssh -q ${sci_host} code/ml-downscaling-emulation/sci-jasmin-script ${variable} ${year} ${sf}

ssh -q -J seis bp mkdir -p $(dirname ${local_filepath})
ssh -a ${xfer_host} scp -oProxyJump=seis {remote_filepath} bp:${local_filepath}

rm ${remote_filepath}
