#! /usr/bin/env bash

eval "$(conda shell.bash hook)"

conda activate downscaling

set -euxo pipefail

mlde moose convert --variable $1 --year $2
mlde moose preprocess --variable $1 --year $2 --scale-factor $3 --subdomain london
mlde moose clean --variable $1 --year $2
