#! /usr/bin/env bash

eval "$(conda shell.bash hook)"

conda activate downscaling

set -euxo pipefail

variable=$1
year=$2

mlde moose convert --variable ${variable} --year ${year}
for sf in 4 8 16 27 32; do
  mlde moose preprocess --variable ${variable} --year ${year} --scale-factor ${sf} --subdomain london
done;
mlde moose clean --variable ${variable} --year ${year}
