variable: tempgrad500250
attrs:
  units: K
  standard_name: air_temperature_difference_500hPa_250hPa
  grid_mapping: rotated_latitude_longitude
sources:
  type: bp
  collection: land-cpm
  variables:
    # assumes already extracted and converted to nc
    # implicit here is rename variable
    - name: temp500
      frequency: day
    - name: temp250
      frequency: day
spec:
  - action: diff
    params:
      left: temp500
      right: temp250
      new_variable: tempgrad500250
  # implicit final actions: assign attrs, save, cleanup extraction?
