variable: tempgrad925850
attrs:
  units: K
  standard_name: air_temperature_difference_925hPa_850hPa
  grid_mapping: rotated_latitude_longitude
sources:
  type: bp
  collection: land-cpm
  variables:
    # assumes already extracted and converted to nc
    # implicit here is rename variable
    - name: temp925
      frequency: day
    - name: temp850
      frequency: day
spec:
  - action: diff
    params:
      left: temp925
      right: temp850
      new_variable: tempgrad925850
  # implicit final actions: assign attrs, save, cleanup extraction?
