variable: temp500
attrs:
  units: K
  standard_name: air_temperature_500hPa
  grid_mapping: rotated_latitude_longitude
sources:
  type: moose
  collection: land-cpm
  variables:
    # assumes already extracted and converted to nc
    # implicit here is rename variable
    - temp500
spec:
  - action: coarsen
    parameters:
      scale_factor: $scale_factor
      grid: vorticity850
  - action: regrid_to_target
  - action: select-subdomain
    parameters:
      domain: $domain
  # implicit final actions: assign attrs, save, cleanup extraction?
