variable: tempgrad850700
attrs:
  units: K
  standard_name: air_temperature_difference_850hPa_700hPa
  grid_mapping: rotated_latitude_longitude
sources:
  type: bp
  collection: land-cpm
  variables:
    # assumes already extracted and converted to nc
    # implicit here is rename variable
    - name: temp700
      frequency: day
    - name: temp850
      frequency: day
spec:
  - action: diff
    params:
      left: temp850
      right: temp700
      new_variable: tempgrad850700
  # implicit final actions: assign attrs, save, cleanup extraction?
