variable: vorticity500
attrs:
  units: s-1
  standard_name: relative_vorticity_500hPa
  grid_mapping: rotated_latitude_longitude
sources:
  type: moose
  collection: land-cpm
  variables:
    # assumes already extracted and converted to nc
    # implicit here is rename variable
    - name: xwind500
      frequency: day
    - name: ywind500
      frequency: day
spec:
  - action: coarsen
    parameters:
      scale_factor: $scale_factor
      grid: vorticity850
      variables: [xwind, ywind]
  - action: vorticity
    parameters:
      theta: 500
  - action: regrid_to_target
  - action: select-subdomain
    parameters:
      domain: $domain
  # implicit final actions: assign attrs, save, cleanup extraction?
