#! /usr/bin/env bash

eval "$(conda shell.bash hook)"

conda activate cuda-downscaling

set -euo pipefail

domain="birmingham"
scale_factor="gcm"
target_resolution="2.2km-coarsened-4x"
target_size=64
variable="~/code/ml_downscaling_emulator/src/ml_downscaling_emulator/config/variables/day/land-cpm/spechum250.yml"

years=$@

python master-script --variable-config ${variable} --domain ${domain} --scale-factor ${scale_factor} --target-resolution ${target_resolution} --target-size ${target-size} ${years}
