#! /usr/bin/env bash

set -euo pipefail

job_id=0

years=$(seq 1981 1 1990)

job_id=$(./queue-dep -j ${job_id} -- ./batch-wrapper ${years})

years=$(seq 1991 1 2000)

job_id=$(./queue-dep -j ${job_id} -- ./batch-wrapper ${years})
