#! /usr/bin/env bash

bp_host="bp"
xfer_host="xfer1.jasmin.ac.uk"

jasmin_filepath=$1
bp_filepath=$2

set -euo pipefail

ssh -a -J seis ${bp_host} mkdir -p $(dirname ${bp_filepath})
set -x
scp -oProxyJump=seis ${xfer_host}:${jasmin_filepath} ${bp_host}:${bp_filepath}
