#! /usr/bin/env bash

eval "$(conda shell.bash hook)"

conda activate downscaling

set -euo pipefail

mass_host="mass-cli.jasmin.ac.uk"
sci_host="sci2.jasmin.ac.uk"
xfer_host="xfer1.jasmin.ac.uk"

year=$1

set -x

# Extract (x and y wind components from moose to nc format)
# for variable in xwind ywind; do
#   LANG=C ssh -a -o ServerAliveInterval=60 ${mass_host} code/ml-downscaling-emulation/moose-etl/extract-script ${variable} ${year}

#   mlde moose convert --variable ${variable} --year ${year}
# done;

variable="vorticity"
domain="london"

# Transform (into vorticity on sci JASMIN)
for sf in 4 8 16 27 32; do
  mlde moose create-variable --variable ${variable} --year ${year} --scale-factor ${sf} --domain ${domain}
done;

# Load (vorticity onto BP storage)
LANG=C ssh -a -o ServerAliveInterval=60 ${xfer_host} code/ml-downscaling-emulation/moose-etl/xfer-script ${variable} ${year}

# Clean up (x and y wind components downloaded from moose)
for variable in xwind ywind; do
  mlde moose clean --variable ${variable} --year ${year}
done
