#! /usr/bin/env bash

eval "$(conda shell.bash hook)"

conda activate downscaling

bp_host="bp"

jasmin_filepath=$1
bp_filepath=$2

set -euo pipefail

set -x

ssh -a -J seis ${bp_host} mkdir -p $(dirname ${bp_filepath})
# mkdir -p $(dirname ${bp_filepath})
scp -oProxyJump=seis ${jasmin_filepath} ${bp_host}:${bp_filepath}
# scp -a ${xfer_host}:${jasmin_filepath} bp:${bp_filepath}
rm ${jasmin_filepath}
# LANG=C ssh -a -q ${sci_host} rm ${jasmin_filepath}
