variable: linpr
attrs:
  units: kg m-2 s-1
  standard_name: precipitation_flux
  grid_mapping: rotated_latitude_longitude
sources:
  type: moose
  collection: land-gcm
  variables:
    # assumes already extracted and converted to nc
    # implicit here is rename variable
    - name: pr
      frequency: day
spec:
  - action: rename
    mapping: {"pr": "linpr"}
  - action: regrid_to_target
    variable: linpr
    parameters:
      scheme: linear
  - action: select-subdomain
    parameters:
      domain: $domain
