variable: tempgrad700500
attrs:
  units: K
  standard_name: air_temperature_difference_700hPa_500hPa
  grid_mapping: rotated_latitude_longitude
sources:
  type: bp
  collection: land-gcm
  variables:
    # assumes already extracted and converted to nc
    # implicit here is rename variable
    - name: temp500
      frequency: day
    - name: temp700
      frequency: day
spec:
  - action: diff
    params:
      left: temp700
      right: temp500
      new_variable: tempgrad700500
  # implicit final actions: assign attrs, save, cleanup extraction?
