variable: vorticity850
attrs:
  units: s-1
  standard_name: relative_vorticity_850hPa
  grid_mapping: rotated_latitude_longitude
sources:
  type: moose
  collection: land-gcm
  variables:
    # assumes already extracted and converted to nc
    # implicit here is rename variable
    - name: xwind
      frequency: day
    - name: ywind
      frequency: day
spec:
  - action: constrain
    query: {pressure: 850.0}
  - action: vorticity
  - action: regrid_to_target
  - action: select-subdomain
    parameters:
      domain: $domain
  # implicit final actions: assign attrs, save, cleanup extraction?
