variable: vorticity925
attrs:
  units: s-1
  standard_name: relative_vorticity_925hPa
  grid_mapping: rotated_latitude_longitude
sources:
  type: moose
  collection: land-gcm
  variables:
    # assumes already extracted and converted to nc
    # implicit here is rename variable
    - name: xwind925
      frequency: day
    - name: ywind925
      frequency: day
spec:
  - action: vorticity
  - action: regrid_to_target
  - action: select-subdomain
    parameters:
      domain: $domain
  # implicit final actions: assign attrs, save, cleanup extraction?
