variable: pr
attrs:
  units: kg m-2 s-1
  standard_name: precipitation_flux
  grid_mapping: rotated_latitude_longitude
sources:
  type: moose
  collection: land-cpm
  variables:
    # assumes already extracted and converted to nc
    # implicit here is rename variable
    - lssnow
    - lsrain
spec:
  - action: coarsen
    parameters:
      scale_factor: $scale_factor
  - action: sum
    variables: [lssnow, lsrain]
  - action: regrid_to_target
    variable: pr
  - action: select-subdomain
    parameters:
      domain: $domain
