variable: wetbulbpott850
attrs:
  units: K
  standard_name: wet_bulb_potential_temperature
  grid_mapping: rotated_latitude_longitude
sources:
  type: moose
  collection: land-cpm
  variables:
    # assumes already extracted and converted to nc
    # implicit here is rename variable
    - wetbulbpott
spec:
  - action: constrain
    query: {pressure: 850.0}
  - action: rename
    mapping: {"wetbulbpott": "wetbulbpott850"}
  - action: coarsen
    parameters:
      scale_factor: $scale_factor
      grid: pr
  - action: regrid_to_target
  - action: select-subdomain
    parameters:
      domain: $domain
  # implicit final actions: assign attrs, save, cleanup extraction?
