variable: pr
attrs:
  units: kg m-2 s-1
  standard_name: precipitation_flux
  grid_mapping: rotated_latitude_longitude
sources:
  type: moose
  collection: gcm
  variables:
    # assumes already extracted and converted to nc
    # implicit here is rename variable
    - pr
spec:
  - action: regrid
    variable: pr
  - action: select-subdomain
    parameters:
      domain: $domain
