variable: pr
attrs:
  units: kg m-2 s-1
  standard_name: pr
  grid_mapping: rotated_latitude_longitude
sources:
  moose:
    # implicit here is extract from moose, convert to nc and rename variable
    - lssnow
    - lsrain
spec:
  - action: sum
    variables: [lssnow, lsrain]
  - action: select-subdomain
    parameters:
      domain: $domain
