variable: vorticity850
attrs:
  units: s-1
  standard_name: relative_vorticity_850hPa
  grid_mapping: rotated_latitude_longitude
sources:
  moose:
    # implicit here is extract from moose, convert to nc and rename variable
    - xwind
    - ywind
spec:
  - action: constrain
    query: {pressure: 850.0}
  - action: coarsen
    parameters:
      scale_factor: $scale_factor
  - action: vorticity
  - action: regrid
    variable: vorticity850
  - action: select-subdomain
    parameters:
      domain: $domain
  # implicit final actions: assign attrs, save, cleanup extraction?
