#! /usr/bin/env bash

set -euo pipefail

collection="land-cpm"
variable="temp250"
domain="birmingham"
variable_sf="gcm"
target_sf=4
size=64

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

MASTER_SCRIPT_PATH="${SCRIPT_DIR}/../master-script"

ts1jobid=$(sbatch -A mass -p mass --time 48:00:00 --parsable ${MASTER_SCRIPT_PATH} -c ${collection} -v ${variable} -s ${variable_sf} -t ${target_sf} -d ${domain} -p ${size} $(seq 1994 1 2000))
echo ${ts1jobid}

ts2jobid=$(sbatch -A mass -p mass --time 48:00:00 --parsable --dependency=afterok:${ts1jobid} ${MASTER_SCRIPT_PATH} -c ${collection} -v ${variable} -s ${variable_sf} -t ${target_sf} -d ${domain} -p ${size} $(seq 2021 1 2040))
echo ${ts2jobid}

ts3jobid=$(sbatch -A mass -p mass --time 48:00:00 --parsable --dependency=afterok:${ts2jobid} ${MASTER_SCRIPT_PATH} -c ${collection} -v ${variable} -s ${variable_sf} -t ${target_sf} -d ${domain} -p ${size} $(seq 2061 1 2080))
echo ${ts3jobid}