#! /usr/bin/env bash

set -euo pipefail

collection="land-cpm"
variable="vorticity850"
domain="birmingham"
variable_sf="gcm"
target_sf=1
size=256

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

${SCRIPT_DIR}/../queue-dep ${collection} ${variable} ${domain} ${variable_sf} ${target_sf} ${size}
