#! /usr/bin/env bash

set -euo pipefail

collection="land-cpm"
variable="pr"
domain="birmingham"
variable_sf=4
target_sf=${variable_sf}
size=64

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

${SCRIPT_DIR}/../queue-dep ${collection} ${variable} ${domain} ${variable_sf} ${target_sf} ${size}
