domain: london
frequency: day
ensemble_member: "01"
scenario: rcp85
resolution: 2.2km-coarsened-27x
predictand:
  variable: pr
  resolution: 2.2km
predictors:
  - variable: vorticity850
split_scheme: random
