domain: london
frequency: day
ensemble_member: "01"
scenario: rcp85
resolution: 60km-2.2km
predictand:
  variable: pr
  resolution: 2.2km-2.2km
predictors:
  - variable: vorticity850
split_scheme: random
