#! /usr/bin/env bash

set -euo pipefail

collection="land-gcm"
variable="vorticity850"
domain="birmingham"
variable_sf=1
target_sf=1
size=256

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

${SCRIPT_DIR}/../queue-dep ${collection} ${variable} ${domain} ${variable_sf} ${target_sf} ${size}
