#! /usr/bin/env bash

eval "$(conda shell.bash hook)"

conda activate cuda-downscaling

set -euo pipefail

mass_host="mass-cli.jasmin.ac.uk"
sci_host="sci2.jasmin.ac.uk"
xfer_host="xfer1.jasmin.ac.uk"

year=$1

collection="land-gcm"
data_variable="vorticity850"
variable_config_name="gcm-${data_variable}"
domain="london"
frequency="day"
src_vars=(xwind ywind)
target_sfs=(1 2 4 8)

let "start_year=year-1"

set -x

# Extract (source data from moose to nc format)
for src_variable in ${src_vars[@]}; do
  mlde moose extract --variable  ${src_variable} --year ${year} --collection ${collection}

  mlde moose convert --variable ${src_variable} --year ${year} --collection ${collection}
done;

# Transform (into vorticity on sci JASMIN)
for target_sf in ${target_sfs[@]}; do
  if [ $target_sf -eq 1 ]; then
    target_resolution="2.2km"
  else
    target_resolution="2.2km-coarsened-${target_sf}x"
  fi
  variable_resolution="60km"

  resolution="${variable_resolution}-${target_resolution}"

  mlde moose create-variable --variable ${variable_config_name} --year ${year} --scale-factor 0 --domain ${domain} --target-resolution ${target_resolution}

  filename="${data_variable}_rcp85_${collection}_${domain}_${resolution}_01_${frequency}_${start_year}1201-${year}1130.nc"
  file_subpath="${domain}/${resolution}/rcp85/01/${data_variable}/${frequency}/${filename}"
  jasmin_filepath="/home/users/vf20964/derived_data/moose/${file_subpath}"
  bp_filepath="/user/work/vf20964/moose/${file_subpath}"

  # Load (vorticity onto BP storage)
  LANG=C ssh -a -o ServerAliveInterval=60 ${xfer_host} code/ml-downscaling-emulation/moose-etl/xfer-script ${jasmin_filepath} ${bp_filepath}
  # Cleanup file copied to BP
  rm ${jasmin_filepath}
done;

# Clean up (x and y wind components downloaded from moose)
for src_variable in ${src_vars[@]}; do
  mlde moose clean --variable ${src_variable} --year ${year} --collection ${collection}
done
