#! /usr/bin/bash

set -euo pipefail

ts1jobid=$(sbatch -A mass -p mass --time 23:00:00 --parsable ts1.batch)
echo ${ts1jobid}

ts2jobid=$(sbatch -A mass -p mass --time 23:00:00 --parsable --dependency=afterok:${ts1jobid} ts2.batch)
echo ${ts2jobid}

ts3jobid=$(sbatch -A mass -p mass --time 23:00:00 --parsable --dependency=afterok:${ts2jobid} ts3.batch)
echo ${ts3jobid}
