name: CI

on: [push]

jobs:
  ci-checks:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - name: Clone repo
      uses: actions/checkout@v2
    - name: Set up Pixi
      uses: prefix-dev/setup-pixi@v0.8.8
      with:
        pixi-version: v0.46.0
        cache: false
        environments: test
        activate-environment: true
    - name: Run tests
      run: pixi run test
