name: Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Black
        uses: psf/black@stable
      - name: Install flake8
        run: pip install flake8
      - name: Flake8
        uses: suo/flake8-github-action@v1
